package com.curso.domain;

public interface CONSTANTESQ {
	
	String SEC = "SELECT * FROM MTS_CURSO_ROLES";
    String UPD = "UPDATE MTS_CURSO_ROLES SET DS_ROL=? WHERE CVE_ROL=?";
	String SECEL  = "SELECT * FROM MTS_CURSO_ROLES WHERE CVE_ROL=?";
	String INS = "INSERT INTO MTS_CURSO_ROLES (CVE_ROL,DS_ROL, ESTATUS) VALUES(?,?,?)";
	String INS2 = "INSERT INTO MTS_CURSO_ROLES (CVE_ROL,DS_ROL) VALUES(?,?)";
	
	String EST="SELECT DISTINCT ESTATUS FROM MTS_CURSO_ROLES"; 
	
	String ROLEST ="SELECT CVE_ROL, DS_ROL FROM MTS_CURSO_ROLES WHERE ESTATUS=?";
	
	String INSEST= "INSERT INTO MTS_CURSO_ESTADO (CVE_ESTADO,NOMBRE_EST,CVE_PAIS) VALUES (?,?,?)";
	String UPDEST = "UPDATE MTS_CURSO_ESTADO SET NOMBRE_EST= ?, CVE_PAIS= ? WHERE CVE_ESTADO = ?";
	String SELECTEST ="SELECT * FROM MTS_CURSO_ESTADO";
	String ESTSEL = "SELECT * FROM mts_curso_estado WHERE cve_pais= ?";
			
}
